#!/usr/bin/env python3
"""Regenerate site/data.js from SDI_2.0.csv.

Run from anywhere; paths are script-relative:
    python3 build_data.py
"""
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "SDI_2.0.csv")
OUT = os.path.join(HERE, "site", "data.js")


def main():
    rows = []
    with open(SRC, newline="") as f:
        for row in csv.DictReader(f):
            rows.append(row)

    years = sorted({int(r["year"]) for r in rows})
    states = {}
    for r in rows:
        st = r["st"]
        entry = states.setdefault(
            st,
            {
                "name": r["state"],
                "mcmc": [None] * len(years),
                "sd": [None] * len(years),
                "additive": [None] * len(years),
            },
        )
        i = years.index(int(r["year"]))
        entry["mcmc"][i] = round(float(r["democracy_mcmc"]), 4)
        entry["sd"][i] = round(float(r["democracy_mcmc_sd"]), 4)
        entry["additive"][i] = round(float(r["democracy_additive"]), 4)

    payload = {"years": years, "states": states}
    with open(OUT, "w") as f:
        f.write("// Generated by build_data.py from SDI_2.0.csv — do not edit by hand.\n")
        f.write("window.SDI = ")
        f.write(json.dumps(payload, separators=(",", ":")))
        f.write(";\n")
    n = len(states)
    print(f"Wrote {OUT}: {n} states x {len(years)} years")


if __name__ == "__main__":
    main()
