#!/usr/bin/env python3
"""Regenerate docs/data.js from SDI_2.0.csv.

Run from anywhere; paths are script-relative:
    python3 build_data.py
"""
import csv
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "SDI_2.0.csv"
OUT = HERE / "docs" / "data.js"


def main():
    with SRC.open(newline="") as f:
        rows = list(csv.DictReader(f))

    years = sorted({int(r["year"]) for r in rows})
    states = {}
    for r in rows:
        st = r["st"]
        entry = states.setdefault(
            st,
            {
                "name": r["state"],
                "mcmc": [None] * len(years),
                "sd": [None] * len(years),
                "additive": [None] * len(years),
            },
        )
        i = years.index(int(r["year"]))
        entry["mcmc"][i] = round(float(r["democracy_mcmc"]), 4)
        entry["sd"][i] = round(float(r["democracy_mcmc_sd"]), 4)
        entry["additive"][i] = round(float(r["democracy_additive"]), 4)

    payload = json.dumps({"years": years, "states": states}, separators=(",", ":"))
    OUT.write_text(
        "// Generated by build_data.py from SDI_2.0.csv — do not edit by hand.\n"
        f"window.SDI = {payload};\n"
    )
    print(f"Wrote {OUT}: {len(states)} states x {len(years)} years")


if __name__ == "__main__":
    main()
